[package]
name = "rsplayer"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
fastrand = "2.2.0"
rodio = { version = "0.20.1", features = [ "symphonia-all" ] }

[dependencies.symphonia-core]
version = "0.5.4"
features = [ "opt-simd-avx", "opt-simd-neon", "opt-simd-sse" ]

[target.'cfg(windows)'.dependencies]
winapi = "0.3.9"

[target.'cfg(unix)'.dependencies]
signal-hook = "0.3.17"
